language: emacs-lisp

script:
  - emacs --version
  - make test

env:
  matrix:
    - EVM_EMACS=emacs-24.5-bin
    - EVM_EMACS=emacs-24.4-bin
    - EVM_EMACS=emacs-git-snapshot
matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot

sudo: required
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask

notifications:
  email: false
